[package]
name = "my_first_parser_1wannabebetter1"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Basic parser that uses peg crate and code example from its documentation"


[dependencies]
peg = "0.8.4"
